### ISSUE TITLE
关于所给的数据集的问题。

### ISSUE THREAD

**Issue by zyrant** [wangxiao5791509/cmSalGAN_PyTorch#1]
您好
      我尝试使用您的代码，但是发现您所给的数据集中不包含.lst文件。

**Comment by wangxiao5791509** [comment]
Sorry for the late response, I didn't notice this issue. We will update this file soon. @zzzyy1997

**Comment by wangxiao5791509** [comment]
Sorry for the later response, because I didn't notice this issue at all. We have updated this file into this github. Thanks for your attention on our work. You can check them, and see if this will help your experiments.

**Comment by wangxiao5791509** [comment]
Sorry for the late response, because I didn't notice this issue at all. We have updated this file into this github. Thanks for your attention on our work. You can check them, and see if this will help your experiments.

@zzzyy1997

**Comment by zyrant** [comment]
代码已经可以运行了，感谢王老师的工作！

**Comment by wangxiao5791509** [comment]
@zzzyy1997 Cool ! Thanks.
